language: node_js
node_js: ["0.12", "0.11", "0.10"]

addons:
  code_climate:
    repo_token: e70846260cd8ce4383449ccb221a088f1e6c93edbf1bb4aced4937cc46b79d21

before_script:
- npm install -g istanbul
- npm install -g codeclimate-test-reporter

after_success:
  - npm run-script cover
  - codeclimate-test-reporter < ./coverage/lcov.info